# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ColorCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_correction_user', models.CharField(max_length=128)),
                ('color_correction_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_user', models.CharField(max_length=128)),
                ('out_for_delivery_date', models.DateField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('bill_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_user', models.CharField(max_length=128)),
                ('layout_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128)),
                ('incoming_date', models.DateField(null=True)),
                ('client_challan_number', models.CharField(max_length=128)),
                ('garment_count', models.IntegerField()),
                ('has_blouse_stitch', models.BooleanField()),
                ('page_count', models.IntegerField()),
                ('book_name', models.CharField(max_length=128)),
                ('book_quantity', models.IntegerField()),
                ('has_photo_lamination', models.BooleanField()),
                ('status', django_fsm.FSMField(choices=[(1, b'Order Created'), (2, b'Sent to Shooting'), (3, b'Shooting Completed'), (4, b'Pose Selection Started'), (5, b'Pose Selection Completed'), (6, b'Pose Cutting Started'), (7, b'Pose Cutting Completed'), (8, b'Layout Creation Started'), (9, b'Layout Creation Completed'), (10, b'Color Correction Started'), (11, b'Color Correction Completed'), (12, b'Dummy Sent to Client'), (13, b'Feedback changes Started'), (14, b'Feedback changes Completed'), (15, b'Printing Started'), (16, b'Printing Completed'), (17, b'Out for delivery'), (18, b'Delivery Done')], default=1, max_length=50)),
                ('binding_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.BindingType')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.GarmentType')),
            ],
        ),
        migrations.CreateModel(
            name='PageQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PoseCutting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_cutting_user', models.CharField(max_length=128)),
                ('pose_cutting_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PoseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_selection_user', models.CharField(max_length=128)),
                ('pose_selection_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_date', models.DateField(null=True)),
                ('folder_number', models.CharField(max_length=128)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting_location', models.IntegerField(choices=[(1, b'Our Studio'), (2, b'Outside Studio')], default=1)),
                ('studio_name', models.CharField(blank=True, max_length=128, null=True)),
                ('model_name', models.CharField(max_length=128)),
                ('shoot_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShootSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ShootType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='worksubtype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.WorkType'),
        ),
        migrations.AddField(
            model_name='shootsubtype',
            name='shoot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ShootType'),
        ),
        migrations.AddField(
            model_name='order',
            name='inner_page_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_page_quality', to='portal.PageQuality'),
        ),
        migrations.AddField(
            model_name='order',
            name='outer_page_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_page_quality', to='portal.PageQuality'),
        ),
        migrations.AddField(
            model_name='order',
            name='shoot_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.ShootSubType'),
        ),
        migrations.AddField(
            model_name='order',
            name='shoot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ShootType'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.WorkSubType'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.WorkType'),
        ),
        migrations.AddField(
            model_name='layout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='feedbackchanges',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='colorcorrection',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
    ]
