# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 14:44
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190309_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Order Created'), (2, b'Sent to Shooting'), (3, b'Shooting Completed'), (4, b'Pose Selection Started'), (5, b'Pose Selection Completed'), (6, b'Pose Cutting Started'), (7, b'Pose Cutting Completed'), (8, b'Layout Creation Started'), (9, b'Layout Creation Completed'), (10, b'Color Correction Started'), (11, b'Color Correction Completed'), (12, b'Dummy Sent to Client'), (13, b'Feedback changes Started'), (14, b'Feedback changes Completed'), (15, b'Printing Started'), (16, b'Printing Completed'), (17, b'Out for delivery'), (18, b'Delivery Done')], default=1),
        ),
    ]
