# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190309_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bill_creation_user', models.CharField(max_length=128)),
                ('bill_number', models.CharField(max_length=128)),
                ('bill_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangesImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('changes_implementation_user', models.CharField(max_length=128)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangesTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('changes_taken_user', models.CharField(max_length=128)),
                ('changes_taken_date', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DummySent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dummy_sent_user', models.CharField(max_length=128)),
                ('dummy_sent_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feedbackchanges',
            name='order',
        ),
        migrations.RemoveField(
            model_name='colorcorrection',
            name='color_correction_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='out_for_delivery_date',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='layout_date',
        ),
        migrations.AddField(
            model_name='posecutting',
            name='number_of_poses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Order Created'), (2, b'Sent to Shooting'), (3, b'Shooting Completed'), (4, b'Pose Selection Started'), (5, b'Pose Selection Completed'), (6, b'Pose Cutting Started'), (7, b'Pose Cutting Completed'), (8, b'Layout Creation Started'), (9, b'Layout Creation Completed'), (10, b'Color Correction Started'), (11, b'Color Correction Completed'), (12, b'Dummy Sent to Client'), (13, b'Changes Taken'), (14, b'Changes Implementation Started'), (15, b'Changes Implementation Completed'), (16, b'Printing Started'), (17, b'Printing Completed'), (18, b'Bill Creation'), (19, b'Delivery Done')], default=1),
        ),
        migrations.DeleteModel(
            name='FeedbackChanges',
        ),
        migrations.AddField(
            model_name='dummysent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='changestaken',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='changesimplementation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='billcreation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
    ]
