# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190309_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posecutting',
            name='pose_cutting_date',
        ),
        migrations.RemoveField(
            model_name='poseselection',
            name='pose_selection_date',
        ),
        migrations.RemoveField(
            model_name='printing',
            name='printing_date',
        ),
        migrations.AddField(
            model_name='printing',
            name='printing_user',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoot',
            name='shoot_user',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shoot_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.ShootSubType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Order Created'), (2, b'Sent to Shooting'), (3, b'Shooting Completed'), (4, b'Pose Selection Started'), (5, b'Pose Selection Completed'), (6, b'Pose Cutting Started'), (7, b'Pose Cutting Completed'), (8, b'Layout Creation Started'), (9, b'Layout Creation Completed'), (10, b'Color Correction Started'), (11, b'Color Correction Completed'), (12, b'Dummy Sent to Client'), (13, b'Changes Taken'), (14, b'Changes Implementation Started'), (15, b'Changes Implementation Completed'), (16, b'Printing Started'), (17, b'Printing Completed'), (18, b'Bill Created'), (19, b'Delivery Done')], default=1),
        ),
    ]
