# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190326_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='binding_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.BindingType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='book_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_challan_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_blouse_stitch',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_photo_lamination',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='incoming_date',
            field=models.DateField(default='1935-11-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='inner_page_quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_page_quality', to='portal.PageQuality'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outer_page_quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer_page_quality', to='portal.PageQuality'),
        ),
        migrations.AlterField(
            model_name='order',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shoot_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.ShootType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.WorkSubType'),
        ),
    ]
