# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190404_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='incoming_date',
            field=models.DateField(default='1935-11-18'),
            preserve_default=False,
        ),
    ]
