# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 14:48
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20190405_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Order Created'), (2, b'Sent to Shooting'), (3, b'Pose Selection Pending'), (4, b'Pose Selection Started'), (5, b'Pose Cutting Pending'), (6, b'Pose Cutting Started'), (7, b'Layout Creation Pending'), (8, b'Layout Creation Started'), (9, b'Color Correction Pending'), (10, b'Color Correction Started'), (11, b'Dummy Sent Pending'), (12, b'Dummy Sent to Client'), (13, b'Changes Taken'), (14, b'Changes Implementation Started'), (15, b'Waiting to send to print'), (16, b'Printing Started'), (17, b'In Delivery'), (18, b'Bill Created'), (19, b'Delivery Done')], default=1),
        ),
    ]
