# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20190405_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poseselection',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poseselection',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
