# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20190405_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcreation',
            name='bill_date',
            field=models.DateTimeField(),
        ),
    ]
