# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20190405_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_path',
            field=models.TextField(null=True),
        ),
    ]
