# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_order_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='s3_key',
            field=models.TextField(null=True),
        ),
    ]
