# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_order_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_photo_size', to='portal.WorkSubType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='portal.WorkSubType'),
        ),
    ]
